### ISSUE TITLE
Plex.TV Metadata API

### ISSUE THREAD

**Issue by zalaghi** [sct/overseerr#4228]
### Description

Failed to retrieve watchlist items

{
 "errorMessage": "Request failed with status code 404"
}

### Version

1.34.0

### Steps to Reproduce

1. Settings
2. Jobs & Cache
3. Plex Watchlist Sync

### Screenshots

<img width="1812" height="950" alt="Image" src="https://github.com/user-attachments/assets/aa7db1a0-8000-45b5-b373-a3eaedcfa50b" />

### Logs

```shell
{
 "errorMessage": "Request failed with status code 404"
}
```

### Platform

desktop

### Device

PC

### Operating System

Fedora

### Browser

Firefox

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by 0xSysR3ll** [comment]
It has been fixed in `develop`, see #4220

**Comment by jadedeane** [comment]
> It has been fixed in `develop`, see [#4220](https://github.com/sct/overseerr/pull/4220)

Per comment [here](https://github.com/sct/overseerr/issues/4224#issuecomment-3217889766), not so sure.

**Comment by tatundria** [comment]
Still not working for me on develop version b1c6e2fdbde49859a661767e9b414555aa7abc31

2025-08-26T13:34:28.331Z [error][Plex.TV Metadata API]: Failed to retrieve watchlist items{"errorMessage":"Request failed with status code 404"}

How can I fix it?

**Comment by 0xSysR3ll** [comment]
> How can I fix it?

Best option is to open a support ticket on discord
